### ISSUE TITLE
MTAG for chrX

### ISSUE THREAD

**Issue by andgan** [omeed-maghzian/mtag#8]
Hi,
I'm not sure if MTAG can be used with chrX, currently passing SNPs in chr X I get the following error:

```
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 0 SNPs remain.
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/wip/aganna/mtag/mtag.py", line 1385, in <module>
    mtag(args)
  File "/humgen/atgu1/fs03/wip/aganna/mtag/mtag.py", line 1245, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "/humgen/atgu1/fs03/wip/aganna/mtag/mtag.py", line 394, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/humgen/atgu1/fs03/wip/aganna/mtag/ldsc_mod/ldscore/sumstats.py", line 422, in estimate_rg
    M_annot, w_ld_cname, ref_ld_cnames, sumstats, _ = _read_ld_sumstats(args, log, None, alleles=True, dropna=True,sumstats=p1)
  File "/humgen/atgu1/fs03/wip/aganna/mtag/ldsc_mod/ldscore/sumstats.py", line 250, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/humgen/atgu1/fs03/wip/aganna/mtag/ldsc_mod/ldscore/sumstats.py", line 235, in _merge_and_log
    raise ValueError(msg.format(N=len(sumstats), F=noun))
ValueError: After merging with reference panel LD, 0 SNPs remain.
Analysis terminated from error at Sun Dec 10 20:06:19 2017
Total time elapsed: 18.38s
```

thanks

**Comment by omeed-maghzian** [comment]
@andgan The problem is that the default LD score reference panel that we use only includes the autosomes. You need to specify an LD score reference panel that has the X chromosome (there is an option for that), though I am not entirely sure that LD Score Regression can use sex chromosomes.

Alternatively, if you think that the amount of inflation does not vary between the X chromosomes and autosomes, you can run MTAG on the autosomes and then use `--resid_covpath` to pass in the resulting sigma_hat matrix into your MTAG run with chrX.

**Comment by andgan** [comment]
Thanks! Option 2 seems realistic in my scenario.
Cheers,
