### ISSUE TITLE
Problem with missing freq column

### ISSUE THREAD

**Issue by chenming9453** [omeed-maghzian/mtag#83]
Hi all,

My summary data lacked the maf column. When I tried to run mtag. I got the following error: 

Traceback (most recent call last):
  File "/ysm-gpfs/pi/zhao/mc2792/software/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/ysm-gpfs/pi/zhao/mc2792/software/mtag/mtag.py", line 1336, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "/ysm-gpfs/pi/zhao/mc2792/software/mtag/mtag.py", line 294, in load_and_merge_data
    raise IOError("--maf_min is specified but maf column is not present in sumstats {}".format(p+1))
IOError: --maf_min is specified but maf column is not present in sumstats 2

I am wondering if the maf column is necessary for mtag? I did not find any flag to avoid using maf.

Best,
Ming

**Comment by paturley** [comment]
MTAG does require the MAF column, but you can use allele frequencies from a
reference panel if you'd like.

**Comment by chenming9453** [comment]
Thank you for your prompt response! And Thank you for the solution.

Best,
Ming

**Comment by divbru** [comment]
Hi, does the --eaf_name require MAF or the effect allele (a1) frequency ? 
The tutorial refers to EAF while the manual (./mtag.py -h) refers to the MAF. Thank you!

**Comment by paturley** [comment]
Ah! Thanks for catching the discrepancy. It should be the effect allele
frequency.
