### ISSUE TITLE
mtga MemoryError

### ISSUE THREAD

**Issue by grazyoshida** [omeed-maghzian/mtag#93]
Hi there,

I am running mgta using two traits and ~1 million of markers.
I met the following error:

Traceback (most recent call last):
  File "./mtag.py", line 1567, in <module>
    mtag(args)
  File "./mtag.py", line 1443, in mtag
    mtag_betas, mtag_se, mtag_factor = mtag_analysis(Zs, Ns, args.omega_hat, args.sigma_hat)
  File "./mtag.py", line 785, in mtag_analysis
    W_N_inv = np.linalg.inv(W_N)
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 445, in inv
    return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
  File "/usr/lib64/python2.7/site-packages/numpy/core/numeric.py", line 1913, in identity
    return eye(n, dtype=dtype)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/twodim_base.py", line 210, in eye
    m = zeros((N, M), dtype=dtype)
MemoryError
Analysis terminated from error at Tue May  5 09:21:35 2020
Total time elapsed: 1.0m:27.91s

Can anyone help me?!
Thank you!

GMY

**Comment by paturley** [comment]
Hmm. It looks like your machine is running out of memory. I would think
that you would be OK with just 1M SNPs though. Can you send the complete
log file?

**Comment by bnj50** [comment]
Hi...i have the same issue. exactly how much memory needed for 95 sumstats of 7 Mil markers?
